### ISSUE TITLE
Install backup proxy fail

### ISSUE THREAD

**Issue by bogdantomasciuc** [ronivay/XenOrchestraInstallerUpdater#110]
**OS**: Ubuntu Server 20.04
**Node.js version**: 14.19.0
**Yarn version**: 1.22.17

**Server specs**
2vCPU, 4G RAM

**Issue**
After install proxy the script says that it is waiting for the port to open for a few times and finally it reports the instalation completed fut failed.  
[fail] Installation completed, but looks like there was a problem when starting xo-proxy. Check /opt/XenOrchestraInstallerUpdater/logs/xo-install.log-202203161545 for more details

**Installation logfile**
Attach complete log as a file. 
[xo-install.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/8265204/xo-install.log)

**Comment by bogdantomasciuc** [comment]
[xo-install.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/8265271/xo-install.log)
Realized I uploaded an update attempt. This is the original install log.

**Comment by ronivay** [comment]
Looks like the build method script uses was removed recently. Should be fixed now. You might want to remove the config file from `/root/.config/xo-proxy/config.toml` and the run install again. Let me know how it goes.

There was also another problem i noticed. The installation should've actually exited during the build phase but it didn't. I'll take a look at that later as not really the root cause of this issue.

**Comment by bogdantomasciuc** [comment]
Thanx for the quick reply! I will give it a shot now and return with further feedback.

**Comment by bogdantomasciuc** [comment]
[xo-install.log](https://github.com/ronivay/XenOrchestraInstallerUpdater/files/8269013/xo-install.log)
Still won't build. Fails with:  
[fail] Something went wrong, exiting. Check /opt/XenOrchestraInstallerUpdater/logs/xo-install.log-202203161839 for more details and use rollback feature if needed

[fail] Removing /opt/xo/xo-builds/xen-orchestra-202203161839 because of failed installation.

**Comment by ronivay** [comment]
Do you get command not found error if you try to run `dmidecode -t system` ? if yes, then you should be able to fix this by running `apt install -y dmidecode` and then run install again. I'll add a fix for that if it's the cause.

**Comment by bogdantomasciuc** [comment]
The command `dmidecode -t system` works.  
![image](https://user-images.githubusercontent.com/23525491/158674871-88d7037a-0bcc-462d-a13d-8fdc9c7ba04c.png)

**Comment by ronivay** [comment]
Interesting. It was proxy token generation that failed. Works fine on Debian, not on Ubuntu. Maybe now? :)

**Comment by bogdantomasciuc** [comment]
[..] Running installation
Fingers crossed.
